site_name: Pygmy Documentation

nav:
- Home: index.md
theme: readthedocs

nav:
  - index.md
  - Installation: installation.md
  - Usage: usage.md
  - Update: update.md
  - Troubleshooting: troubleshooting.md
  - SSH Agent: ssh_agent.md

markdown_extensions:
    - toc:
        permalink: true
        baselevel: 1
    - admonition
